name: Biology Agent
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -U google-generativeai
      - name: Run Agent
        env:
          GEMINI_API_KEY: ${{ AIzaSyBZUgx5cBvJLIruuWtlUS0AWaR3lUMSpyQ }}
        run: python main.py
      - name: Save Result
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "New Video Plan" || echo "No changes"
          git push
